apiVersion: apps/v1
kind: Deployment
metadata:
  name: cryptospins-api
  namespace: default
  labels:
    app: cryptospins-api
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cryptospins-api
  template:
    metadata:
      labels:
        app: cryptospins-api
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8000"
    spec:
      containers:
      - name: api
        image: 269599744150.dkr.ecr.us-east-1.amazonaws.com/cryptospins-api:c5c02785318925bc5104a553c9e4937b22901213
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: ENV
          value: "production"
        - name: LOG_LEVEL
          value: "INFO"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
      restartPolicy: Always