apiVersion: v1
kind: Service
metadata:
  name: cryptospins-api
  namespace: default
  labels:
    app: cryptospins-api
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: cryptospins-api
---
apiVersion: v1
kind: Service
metadata:
  name: cryptospins-api-internal
  namespace: default
  labels:
    app: cryptospins-api
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: cryptospins-api