global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'cleointhecloud.1@gmail.com'
  smtp_auth_username: 'cleointhecloud.1@gmail.com'
  smtp_auth_password: 'mwfq ygve jboq cfsy'
  smtp_require_tls: true

route:
  receiver: 'email-notifications'
  group_by: ['alertname', 'service', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  routes:
  - match:
      severity: critical
    receiver: 'critical-email'
    group_wait: 10s
    repeat_interval: 1h
  - match:
      severity: warning  
    receiver: 'warning-email'
    group_wait: 30s
    repeat_interval: 3h
  - match:
      severity: info
    receiver: 'info-email'
    group_wait: 1m
    repeat_interval: 6h

receivers:
- name: 'critical-email'
  email_configs:
  - to: 'cleointhecloud.1@gmail.com'
    subject: '🚨 CRITICAL ALERT: {{ .GroupLabels.alertname }}'
    headers:
      Subject: '🚨 CRITICAL: {{ .CommonLabels.alertname }} - {{ .CommonAnnotations.summary }}'
    html: |
      <!DOCTYPE html>
      <html>
      <body>
        <h2 style="color: #d73027;">🚨 CRITICAL ALERT</h2>
        <p><strong>Alert:</strong> {{ .CommonLabels.alertname }}</p>
        <p><strong>Summary:</strong> {{ .CommonAnnotations.summary }}</p>
        <p><strong>Description:</strong> {{ .CommonAnnotations.description }}</p>
        <p><strong>Service:</strong> {{ .CommonLabels.service }}</p>
        <p><strong>Severity:</strong> {{ .CommonLabels.severity }}</p>
        
        <h3>Alert Details:</h3>
        <ul>
        {{ range .Alerts }}
          <li>
            <strong>Status:</strong> {{ .Status }}<br>
            <strong>Started:</strong> {{ .StartsAt }}<br>
            {{ if .EndsAt }}
            <strong>Ended:</strong> {{ .EndsAt }}<br>
            {{ end }}
            <strong>Labels:</strong>
            <ul>
            {{ range .Labels.SortedPairs }}
              <li>{{ .Name }}: {{ .Value }}</li>
            {{ end }}
            </ul>
          </li>
        {{ end }}
        </ul>
        
        <p><em>This is an automated alert from CryptoSpins monitoring system.</em></p>
      </body>
      </html>

- name: 'warning-email'  
  email_configs:
  - to: 'cleointhecloud.1@gmail.com'
    subject: '⚠️  WARNING: {{ .GroupLabels.alertname }}'
    headers:
      Subject: '⚠️  WARNING: {{ .CommonLabels.alertname }} - {{ .CommonAnnotations.summary }}'
    html: |
      <!DOCTYPE html>
      <html>
      <body>
        <h2 style="color: #ff8c00;">⚠️  WARNING ALERT</h2>
        <p><strong>Alert:</strong> {{ .CommonLabels.alertname }}</p>
        <p><strong>Summary:</strong> {{ .CommonAnnotations.summary }}</p>
        <p><strong>Description:</strong> {{ .CommonAnnotations.description }}</p>
        <p><strong>Service:</strong> {{ .CommonLabels.service }}</p>
        <p><strong>Severity:</strong> {{ .CommonLabels.severity }}</p>
        
        <h3>Alert Details:</h3>
        <ul>
        {{ range .Alerts }}
          <li>
            <strong>Status:</strong> {{ .Status }}<br>
            <strong>Started:</strong> {{ .StartsAt }}<br>
            {{ if .EndsAt }}
            <strong>Ended:</strong> {{ .EndsAt }}<br>
            {{ end }}
          </li>
        {{ end }}
        </ul>
        
        <p><em>This is an automated alert from CryptoSpins monitoring system.</em></p>
      </body>
      </html>

- name: 'info-email'
  email_configs:
  - to: 'cleointhecloud.1@gmail.com'
    subject: 'ℹ️  INFO: {{ .GroupLabels.alertname }}'
    headers:
      Subject: 'ℹ️  INFO: {{ .CommonLabels.alertname }} - {{ .CommonAnnotations.summary }}'
    html: |
      <!DOCTYPE html>
      <html>
      <body>
        <h2 style="color: #4285f4;">ℹ️  INFO ALERT</h2>
        <p><strong>Alert:</strong> {{ .CommonLabels.alertname }}</p>
        <p><strong>Summary:</strong> {{ .CommonAnnotations.summary }}</p>
        <p><strong>Description:</strong> {{ .CommonAnnotations.description }}</p>
        <p><strong>Service:</strong> {{ .CommonLabels.service }}</p>
        
        <p><em>This is an informational alert from CryptoSpins monitoring system.</em></p>
      </body>
      </html>

- name: 'email-notifications'
  email_configs:
  - to: 'cleointhecloud.1@gmail.com'
    subject: '{{ .CommonLabels.severity | toUpper }}: {{ .CommonAnnotations.summary }}'
    headers:
      Subject: '{{ .CommonLabels.severity | toUpper }}: {{ .CommonLabels.alertname }} - {{ .CommonAnnotations.summary }}'
    html: |
      <!DOCTYPE html>
      <html>
      <body>
        <h2>{{ .CommonLabels.alertname }}</h2>
        <p><strong>Summary:</strong> {{ .CommonAnnotations.summary }}</p>
        <p><strong>Description:</strong> {{ .CommonAnnotations.description }}</p>
        <p><strong>Service:</strong> {{ .CommonLabels.service }}</p>
        <p><strong>Severity:</strong> {{ .CommonLabels.severity }}</p>
        
        <h3>Alert Details:</h3>
        <pre>{{ range .Alerts }}{{ .Annotations }}{{ end }}</pre>
        
        <p><em>This is an automated alert from CryptoSpins monitoring system.</em></p>
      </body>
      </html>