apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: cryptospins-api-alerts
  namespace: monitoring
  labels:
    app: cryptospins-api
    release: kube-prom
    prometheus: kube-prometheus-stack-prometheus
spec:
  groups:
  - name: cryptospins.api.health
    rules:
    - alert: CryptoSpinsAPIDown
      expr: up{service="cryptospins-api"} == 0
      for: 1m
      labels:
        severity: critical
        service: cryptospins-api
      annotations:
        summary: "CryptoSpins API is down"
        description: "CryptoSpins API has been down for more than 1 minute"
        
    - alert: CryptoSpinsAPIHighErrorRate
      expr: rate(http_requests_total{service="cryptospins-api",status_code=~"5.."}[5m]) / rate(http_requests_total{service="cryptospins-api"}[5m]) > 0.05
      for: 2m
      labels:
        severity: warning
        service: cryptospins-api
      annotations:
        summary: "High error rate in CryptoSpins API"
        description: "CryptoSpins API error rate is above 5% for the last 5 minutes"
        
    - alert: CryptoSpinsAPIHighLatency
      expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{service="cryptospins-api"}[5m])) > 2
      for: 3m
      labels:
        severity: warning
        service: cryptospins-api
      annotations:
        summary: "High latency in CryptoSpins API"
        description: "CryptoSpins API 95th percentile latency is above 2 seconds"

  - name: cryptospins.business.rules
    rules:
    - alert: UnusualWinRate
      expr: cryptospins_win_rate > 0.4 or cryptospins_win_rate < 0.2
      for: 5m
      labels:
        severity: warning
        service: cryptospins-api
        type: business
      annotations:
        summary: "Unusual win rate detected"
        description: "CryptoSpins win rate is {{ $value | humanizePercentage }} which is outside normal range (20-40%)"
        
    - alert: SuspiciouslyHighBettingVolume
      expr: rate(cryptospins_bets_total[5m]) > 100
      for: 2m
      labels:
        severity: warning
        service: cryptospins-api
        type: business
      annotations:
        summary: "Unusually high betting volume"
        description: "Betting rate is {{ $value | printf \"%.1f\" }} bets/second, which may indicate suspicious activity"
        
    - alert: NoBetsForExtendedPeriod
      expr: increase(cryptospins_bets_total[15m]) == 0
      for: 15m
      labels:
        severity: info
        service: cryptospins-api
        type: business
      annotations:
        summary: "No betting activity"
        description: "No bets have been placed in the last 15 minutes"
        
    - alert: LargeLoss
      expr: (cryptospins_total_profit - cryptospins_total_profit offset 1h) < -10000
      for: 0m
      labels:
        severity: critical
        service: cryptospins-api
        type: business
      annotations:
        summary: "Large loss detected"
        description: "House has lost more than $10,000 in the last hour"

  - name: cryptospins.monitoring.rules
    rules:
    - alert: DeadMansSwitch
      expr: vector(1)
      for: 0m
      labels:
        severity: info
        service: cryptospins-monitoring
        type: monitoring
      annotations:
        summary: "Dead man's switch - monitoring is alive"
        description: "This alert fires continuously. If you stop receiving it, monitoring system is down."
        
  - name: cryptospins.security.rules  
    rules:
    - alert: TooManyFailedRequests
      expr: rate(http_requests_total{service="cryptospins-api",status_code=~"4.."}[5m]) > 50
      for: 2m
      labels:
        severity: warning
        service: cryptospins-api
        type: security
      annotations:
        summary: "High rate of failed requests"
        description: "More than 50 failed requests per second in the last 5 minutes, possible DDoS or brute force attack"
        
    - alert: ResourceExhaustion
      expr: rate(cryptospins_active_users[5m]) > 1000
      for: 1m
      labels:
        severity: critical
        service: cryptospins-api
        type: security
      annotations:
        summary: "Potential resource exhaustion"
        description: "More than 1000 active users, system may be under attack or experiencing unusual load"