apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cryptospins-monitoring
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: "ServerSideApply=true"
spec:
  project: default
  source:
    repoURL: https://github.com/lolearningcode/high-stakes-devops.git
    path: monitoring
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true