apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cryptospins-infrastructure
  namespace: argocd
  labels:
    app: cryptospins-infrastructure
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: 'https://github.com/lolearningcode/high-stakes-devops.git'
    path: terraform/k8s-manifests
    targetRevision: main
    directory:
      recurse: true
      jsonnet: {}
  
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  revisionHistoryLimit: 10
  
---
apiVersion: argoproj.io/v1alpha1
kind: Application  
metadata:
  name: cryptospins-platform
  namespace: argocd
  labels:
    app: cryptospins-platform
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: 'https://github.com/lolearningcode/high-stakes-devops.git'
    path: argo/
    targetRevision: main
    directory:
      recurse: true
  
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  revisionHistoryLimit: 5

---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cryptospins-project
  namespace: argocd
spec:
  description: CryptoSpins High-Stakes DevOps Project
  
  sourceRepos:
  - 'https://github.com/lolearningcode/high-stakes-devops.git'
  - 'https://github.com/lolearningcode/*'
  - 'https://charts.bitnami.com/bitnami'
  - 'https://prometheus-community.github.io/helm-charts'
  - 'https://grafana.github.io/helm-charts'
  
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  
  roles:
  - name: admin
    description: Admin access to CryptoSpins project
    policies:
    - p, proj:cryptospins-project:admin, applications, *, cryptospins-project/*, allow
    - p, proj:cryptospins-project:admin, repositories, *, *, allow
    groups:
    - cryptospins:admin
  
  - name: developer
    description: Developer access to CryptoSpins project
    policies:
    - p, proj:cryptospins-project:developer, applications, get, cryptospins-project/*, allow
    - p, proj:cryptospins-project:developer, applications, sync, cryptospins-project/*, allow
    groups:
    - cryptospins:developer